---
title: "Example"
author: "Gregor Steiner"
date: last-modified
editor: visual
theme: cosmo
toc: true  
number-sections: true
colorlinks: true
highlight-style: pygments
format:
  html: 
    code-fold: true
    code-tools: true
    html-math-method: katex
    self-contained: true
bibliography: references.bib
---

# Simulate Data

Here I try to reproduce the results in Section 5.1 of @evans_didelez_2023. First, we simulate data basd on their running example.

```{r message=FALSE}
library(causl)

forms <- list(L ~ A0, 
              list(A0 ~ 1, A1 ~ A0*L),
              Y ~ A0*A1, 
              ~ A0)

pars <- list(A0 = list(beta = 0),
             L = list(beta = c(0.3,-0.2), phi=1),
             A1 = list(beta = c(-0.3,0.4,0.3,0)),
             Y = list(beta = c(-0.5,0.2,0.3,0), phi=1),
             cop = list(beta = c(1,0.5)))

set.seed(123)
n <- 1e4
dat <- rfrugalParam(n, formulas = forms, pars=pars, 
                    family = list(3,c(5,5),1,1), careful=TRUE)


```

Using inverse probability weighting (IPW), we can check that the causal relationship for $Y$ is correct.

```{r}
glmA1 <- glm(A1 ~ A0*L, family=binomial, data=dat)
ps <- fitted(glmA1)
wt <- dat$A1/ps + (1-dat$A1)/(1-ps)
lm(Y ~ A0 * A1, data = dat, weights = wt) |> summary()

```


# Maximum Likelihood


```{r}
likl <- function(beta_0, beta_a0, beta_a1, beta_a01, sigma){
  with(dat, {
    dnorm(Y, beta_0 + beta_a0*A0 + beta_a1*A1 + beta_a01*A0*A1, sigma) |>
      prod()
    })
}

likl(-0.5, 0.2, 0.3, 0, 0.1)

```




```{r}
fit <- fitCausal(dat, formulas = list(Y ~ A0 * A1, L ~ A0, ~ A0*A1),
                 family = c(1, 3, 1), control=list(maxit=2e4, newton=TRUE))
fit
```





